services:
  pipline:
    build:
      context: .
      dockerfile: Pipeline.Dockerfile
    container_name: pipeline
    depends_on:
      - namenode
      - datanode
    volumes:
      - .:/app
    working_dir: /app
    environment:
      HOST_IP: ${HOST_IP}
    entrypoint: [ "python3", "main.py" ]

  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    env_file: .env
    environment:
      ROLE: ${NAMENODE_ROLE}
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./hadoop/.hadoop.env:/opt/.hadoop.env:ro

  datanode:
    build: .
    container_name: datanode
    hostname: datanode
    env_file: .env
    environment:
      ROLE: ${DATANODE_ROLE}
    volumes:
      - datanode-data:/hadoop/dfs/data
      - ./hadoop/.hadoop.env:/opt/.hadoop.env:ro

volumes:
  namenode-data:
  datanode-data:
