services:
  namenode:
    build:
      context: .
      dockerfile: dockerfiles/namenode.dockerfile
    container_name: namenode
    hostname: namenode
    env_file: .env
    working_dir: /app
    environment:
      ROLE: ${NAMENODE_ROLE}
      HOST_ID: ${HDFS_HOST_IP}
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
      - ./.env:/app/.env:ro
      - ./reviews:/app/reviews

  datanode:
    build:
      context: .
      dockerfile: dockerfiles/datanode.dockerfile
    container_name: datanode
    hostname: datanode
    env_file: .env
    environment:
      ROLE: ${DATANODE_ROLE}
    volumes:
      - datanode-data:/hadoop/dfs/data

volumes:
  namenode-data:
  datanode-data:
