services:
  namenode:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    container_name: namenode
    hostname: namenode
    env_file: .env
    working_dir: /app
    environment:
      ROLE: ${NAMENODE_ROLE}
      HOST_ID: ${HDFS_HOST_IP}
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./hadoop/.hadoop.env:/opt/.hadoop.env:ro
      - .:/app

  datanode:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    container_name: datanode
    hostname: datanode
    env_file: .env
    environment:
      ROLE: ${DATANODE_ROLE}
    volumes:
      - datanode-data:/hadoop/dfs/data
      - ./hadoop/.hadoop.env:/opt/.hadoop.env:ro

volumes:
  namenode-data:
  datanode-data:
